---
- name: Deploy Portainer Stack
  hosts: Chat
  become: true
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  environment: 
    DOCKER_TOKEN: "{{ lookup('env', 'DOCKER_TOKEN') }}"

  tasks:
    - name: Clone the repository
      become: yes
      become_user: root
      shell: cd /root && git clone https://github.com/masluse/ChatWebServer

    - name: Build the Docker image
      become: yes
      become_user: root
      shell: cd /root/ChatWebServer && docker build -t ghcr.io/masluse/chatweb:latest .

    - name: Docker login
      docker_login:
        registry_url: ghcr.io
        username: masluse
        password: "{{ DOCKER_TOKEN }}"
      become: yes

    - name: Push Docker image
      become: yes
      become_user: root
      shell: docker push ghcr.io/masluse/chatweb:latest

    - name: Remove the cloned folder
      become: yes
      become_user: root
      shell: rm -rf /root/test

    - name: Deploy Portainer Stack
      become: yes
      shell: |
        cd /docker/docker-compose/test-deployment/
        docker-compose pull
        docker-compose up --force-recreate --build -d
