---
- hosts: all
  become: yes
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        update_cache: yes

    - name: Pull und run Minecraft Server
      community.docker.docker_container:
        name: mcserver
        image: itzg/minecraft-server
        restart_policy: always
        ports:
          - "25565:25565"
        env:
          EULA: "TRUE"
          VERSION: "1.18.2"
