---
- name: Aktualisiere Portainer
  hosts: Hetzner
  become: true
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Wechseln zum Verzeichnis "/root/portainer"
      become_user: root
      shell: cd /root/portainer

    - name: Aktualisieren des Portainer-Images
      become_user: root
      shell: docker pull portainer/portainer-ce:latest
      args:
        chdir: /root/portainer

    - name: Starten von Portainer
      become_user: root
      shell: docker-compose up
      args:
        chdir: /root/portainer
