---
- name: Update Teleport Client
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Get current Teleport version
      command: tsh version
      register: current_version
      ignore_errors: true

    - name: Get latest Teleport release version
      uri:
        url: https://api.github.com/repos/gravitational/teleport/releases/latest
        return_content: yes
      register: latest_release

    - name: Set latest version
      set_fact:
        latest_version: "{{ latest_release.json.tag_name }}"

    - name: Download Teleport if outdated
      get_url:
        url: "https://get.gravitational.com/teleport-{{ latest_version }}-linux-amd64-bin.tar.gz"
        dest: "/tmp/teleport-{{ latest_version }}.tar.gz"
      when: current_version.rc != 0 or current_version.stdout != latest_version

    - name: Extract Teleport
      unarchive:
        src: "/tmp/teleport-{{ latest_version }}.tar.gz"
        dest: /usr/local/bin
        remote_src: yes
      when: current_version.rc != 0 or current_version.stdout != latest_version

    - name: Clean up tar file
      file:
        path: "/tmp/teleport-{{ latest_version }}.tar.gz"
        state: absent
