- name: Upgrade Ubuntu 22.04 LTS to 24.04 LTS via 23.10
  hosts: all
  become: yes
  tasks:
    - name: Gather current Ubuntu version
      command: lsb_release -rs
      register: current_version

    - name: Gather current Ubuntu version after upgrade to 23.10
      command: lsb_release -rs
      register: current_version_2310
      changed_when: false

    - name: Ensure system is running Ubuntu 23.10
      fail:
        msg: "Upgrade to 23.10 failed."
      when: current_version_2310.stdout != "23.10"

    - name: Set Prompt back to lts after reboot
      lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: 'Prompt=normal'
        line: 'Prompt=lts'

    - name: Start the release upgrade to 24.04 LTS
      command: do-release-upgrade -d -f DistUpgradeViewNonInteractive
      register: upgrade_to_2404_result
      ignore_errors: yes

    - name: Reboot after upgrading to 24.04 LTS
      reboot:
      when: upgrade_to_2404_result is succeeded

    - name: Gather current Ubuntu version after upgrade to 24.04 LTS
      command: lsb_release -rs
      register: current_version_2404
      changed_when: false

    - name: Ensure system is running Ubuntu 24.04 LTS
      fail:
        msg: "Upgrade to 24.04 LTS failed."
      when: current_version_2404.stdout != "24.04"
